---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: run-flake8
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: | 
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . --max-line-length=120